### ISSUE TITLE
Status update on this library

### ISSUE THREAD

**Issue by chshersh** [andreyk0/fcm-client#1]
Is this library maintained? Also, I see commit with `wip` message. Is it finished or still in-progress?

**Comment by andreyk0** [comment]
I've been running a small project using it for a while, haven't needed to change anything yet so no active development.

**Comment by chshersh** [comment]
@andreyk0 Thanks a lot for response! At our company we want to use `firebase` so I'm looking for existing bindings to Firebase API. I discovered 3 Haskell libraries with bindings to `firebase` but other two are not maintained for 2 years already... Could you, please, provide some description on what is implemented in your library and how much API is supported? And which authentication scheme you use?

Probably we could collaborate on this project in order to have complete and maintained `firebase` bindings in Haskell :top:

**Comment by andreyk0** [comment]
Hey! It's been a while but at the time I was only interested in push notifications, so implemented some models to construct them as I was reading the firebase docs.
Auth key (downloaded from the console) is used for authentication.
A sample CLI found in the cli dir is the experimental code I used to try things out and to play with sending batches of push notifications from batch files.

**Comment by chshersh** [comment]
@andreyk0 Are you planning to maintain this library? Do you want to upload it to Hackage/Stackage? If you don't want to work on this library and maintain it anymore our organization can fork this repository, upload it to Hackage and continue its maintenance. Keeping you as an author in `.cabal` file of course.

**Comment by andreyk0** [comment]
Hey!
I'm happy to transfer ownership to you. I don't have the time to work on it right now.
Feel free to fork/publish, etc. When it's done, ping me here, I'll update README to point to your new place.
Thanks!

**Comment by chshersh** [comment]
@andreyk0 These are really great news! I will notify you when we start working on this library 🙂I'm currently reading code and trying to grasp internals.
Meanwhile, could you suggest an easy way to test `fcm-client` and specifically your executable? Some links to resources about running firebase clients are extremely appreciated! 🙏

**Comment by andreyk0** [comment]
Cool!
In terms of testing, overall this is just a glorified JSON layer, could be tested by running through some important permutations of the supported message formats.

CLI doesn't do much either, I guess the least obvious feature is the ability to send input batches, I wrote it more just as an example and a way to quickly send test messages but I guess it could be tested too by injecting google API URL via an environmental variable or something and re-directing traffic to a mock API server, sending a small batch and tallying up the results.

**Comment by chshersh** [comment]
@andreyk0 I've finally forked repository and created PR with related changes:

* https://github.com/Holmusk/fcm-client/pull/1

Let me know if I need to change something regarding maintainer information! If you're okay with changes, I will release this version to Hackage after PR is merged.

**Comment by andreyk0** [comment]
Looks great! Go for it!
